### PR TITLE
Client: Handle ANY and CNAME recursion

### PR DESCRIPTION
**Pull request by cfcs**
- Expose RRs for `ANY` queries
-  resolve returned CNAMEs recursively (currently limited to 20 recursions by policy)
- `odns`:
  - add some more subcommands:
    - `txt`
    - `any`
    - `dkim`
  - fixup man pages a bit
- allow `CNAME`s that are not hostnames (this was in the way of the `DKIM` resolver)

ping @hannesm

### CODE REVIEW

**Comment by cfcs** [comment]
ping @hannesm

**Comment by hannesm** [comment]
CI dislikes:
```
# File "client/udns_client.ml", line 71, characters 10-13:
# Error: The GADT constructor Any of type Dns_map.k
#        must be qualified in this pattern.
```

...on 4.06.0... any hints!?

**Comment by cfcs** [comment]
I'm not smart enough to fix this :-(

**Comment by cfcs** [comment]
OK with the assistance of qualified help I **was** smart enough to look at the new Travis job and realize that the previous commit fixed the issue, but now failed due to the use of `Seq.t` when converting from `Map.t` to `Set.t`.
I switched to using a list instead. Travis seems green :))))

**Pull request merged**
